/*
 * Globalize Culture fr
 *
 * http://github.com/jquery/globalize
 *
 * Copyright Software Freedom Conservancy, Inc.
 * Dual licensed under the MIT or GPL Version 2 licenses.
 * http://jquery.org/license
 *
 * This file was generated by the Globalize Culture Generator
 * Translation: bugs found in this file need to be fixed in the generator
 */

(function( window, undefined ) {

var Globalize;

if ( typeof require !== "undefined" &&
	typeof exports !== "undefined" &&
	typeof module !== "undefined" ) {
	// Assume CommonJS
	Globalize = require( "globalize" );
} else {
	// Global variable
	Globalize = window.Globalize;
}

Globalize.addCultureInfo( "fr", "default", {
	name: "fr",
	englishName: "French",
	nativeName: "français",
	language: "fr",
	messages : {		
		"noResult" : "Aucun résultat",
		"in" : " à ",
		"results" : " résultats ",
		"meter" : "m",
		"displayNumber" : "Afficher le numéro",
		"showDetail" : "Afficher le détail",
		"hideDetail" : "Cacher le détail",
		"itinerary" : "Itinéraire",
		"share" : "Partager",
		"cancel" : "Annuler",
		"discussion" : "Ouvrir une discussion",
		"prevPage" : "Page précédante",
		"nextPage" : "Page suivante",
		"totalPage" : "Nombre total de pages : ",
		"message" : "Message",
		"defaultMessage" : "Voici la fiche du professionnel PagesJaunes : ",
		"space" : "Espace",
		"user" : "Utilisateur",
		"type" : "Type",
		"title" : "Titre",
		"edit" : "Editer",
		"companyAddress" : "Adresse de l'entreprise : ",
	    "save" : "Enregistrer",
	}
});

}( this ));
